superproject/blog/urls.py
from django.urls import include
from django.urls import path
from rest_framework import routers

from blog import views

app_name = "blog"

router = routers.DefaultRouter()
router.register("posts", views.PostViewSet)

urlpatterns = [
    path("", views.AllPostsView.as_view(), name="all"),
    path("<int:pk>/", views.SinglePostView.as_view(), name="single"),
    path("<int:pk>/delete/", views.DeletePostView.as_view(), name="delete"),
    path("<int:pk>/update/", views.UpdatePostView.as_view(), name="update"),
    path("api/", include(router.urls)),
    path("new/", views.CreatePostView.as_view(), name="new"),
]

superproject/project/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.urls import include
from django.urls import path

from project.views import SignUpView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("task4/", include("task4.urls")),
]

superproject/task4/urls.py
from django.urls import path

from task4.views import IndexView
from task4.views import ShowNumbersView
from task4.views import task

urlpatterns = [
    path("", task),
    path("check/", IndexView.as_view()),
    path("info/", ShowNumbersView.as_view()),
]

superproject/task4/models.py
from datetime import datetime
from typing import Optional

from delorean import Delorean
from django.db import models
from pydantic import BaseModel
from pydantic import Field


class Numbers(models.Model):
    name = models.TextField(unique=True)
    n = models.BigIntegerField(default=0)

    def __repr__(self):
        return f"{self.__class__.__name__}(id={self.pk}, name={self.name}, n={self.n})"


def utcnowtz() -> datetime:
    return Delorean().datetime


class CheckManager(models.Manager):
    pass


class Check(models.Model):
    objects = CheckManager()

    name = models.TextField(blank=True, null=True)
    ip = models.TextField(blank=True, null=True)
    service = models.TextField(blank=True, null=True)
    at = models.DateTimeField(default=utcnowtz)
    ok = models.BooleanField(default=False)
    description = models.TextField(blank=True, null=True)
    ms = models.IntegerField(blank=True, null=True)


class CheckT(BaseModel):
    id: Optional[int] = Field(None)
    name: str = Field(...)
    ip: Optional[str] = Field(None)
    service: str = Field(...)
    at: datetime = Field(default_factory=utcnowtz)
    ok: bool = Field(False)
    description: Optional[str] = Field(None)
    ms: int = Field(0)

    class Config:
        orm_mode = True

superproject/task4/views.py
import json
import traceback
from typing import Optional
from typing import Tuple
from typing import Union

from django.core.exceptions import PermissionDenied
from django.http import HttpRequest
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
from django.views.generic import ListView
from ipware import get_client_ip

from task4.models import Check
from task4.models import CheckT
from task4.models import Numbers


def get_user_name(request: HttpRequest) -> Optional[str]:
    name = request.headers.get("x-user") or None
    return name


def set_user_name(response: HttpResponse, name: str) -> None:
    response.headers["x-user"] = name


def add_number(name: str, number: int):
    obj: Tuple[Numbers, bool] = Numbers.objects.get_or_create(name=name)
    rec, _created = obj
    rec.n += number
    rec.save()
    return rec.n


def validate_number(number: int) -> None:
    lower_bound, upper_bound = -100, 100
    if not (lower_bound <= number <= upper_bound):
        raise ValueError(
            f"number {number} is not in range {(lower_bound, upper_bound)}"
        )


def parse_payload(request: HttpRequest) -> Union[str, int, None]:
    if not request.body:
        raise ValueError("non-empty body is required")

    try:
        payload = json.loads(request.body)
    except json.JSONDecodeError as err:
        raise ValueError(f"malformed payload: {request.body!r} ({err})") from err

    if isinstance(payload, int):
        validate_number(payload)
    elif payload != "stop":
        raise ValueError(
            f"value {payload!r} is not acceptable: MUST be either int, or 'stop'"
        )

    return payload


class UnprocessableEntityResponse(JsonResponse):
    status_code = 422


@csrf_exempt
@require_http_methods(["POST"])
def task(request: HttpRequest) -> HttpResponse:
    name = get_user_name(request)
    if not name:
        raise PermissionDenied(json.dumps("header X-USER is not set"))

    try:
        payload = parse_payload(request)
    except ValueError as err:
        response = UnprocessableEntityResponse(str(err), safe=False)
    else:
        if isinstance(payload, int):
            current = add_number(name, payload)
        elif payload == "stop":
            current = add_number(name, 0)
        else:
            current = None

        response = JsonResponse(
            current,
            safe=False,
        )

    set_user_name(response, name)
    return response


@csrf_exempt
def check(request: HttpRequest) -> HttpResponse:
    resp_payload = {"ok": False}

    try:
        ip, _routable = get_client_ip(request)

        obj: CheckT = CheckT.parse_raw(request.body)
        obj.ip = ip

        dbobj = Check(**obj.dict())
        dbobj.save()

        obj = CheckT.from_orm(dbobj)
        resp_payload.update(
            {
                "ok": True,
                "data": obj.dict(),
            }
        )

    except Exception as err:
        resp_payload["description"] = str(err)
        resp_payload["tb"] = traceback.format_exc()

    return JsonResponse(resp_payload, status=200 if resp_payload["ok"] else 500)


class IndexView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        return render(
            request,
            "task4/index.html",
            {
                "object_list": Check.objects.order_by("-at")[:10],
            },
        )

    def post(self, request: HttpRequest) -> HttpResponse:
        return check(request)


class ShowNumbersView(ListView):
    template_name = "task4/numbers.html"
    model = Numbers

superproject/task4/templates/task4/index.html
{% load static %}
{% load tz %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <title>Проверка Task4</title>
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" rel="stylesheet">
    <script crossorigin="anonymous"
            integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"></script>
    <style>
        section {
            padding-bottom: 2em;
            padding-left: 40em;
            padding-right: 1em;
        }
    </style>
</head>
<body>
<div class="container">
    <h1>Проверка Task 4</h1>
    <hr>
    <article>
        <div class="row">
            <section class="col">
                <h2>Что тестим?</h2>
                <div class="mb-3">
                    <label class="form-label" for="id_service">Сервис: </label>
                    <input class="form-control" id="id_service" placeholder="локалхост - ок!" type="url">
                </div>
                <div class="mb-3">
                    <label class="form-label" for="id_name">Пользователь: </label>
                    <input class="form-control" id="id_name" placeholder="пойдёт как X-USER" type="text">
                </div>
                <div class="mb-3">
                    <button class="btn btn-primary" id="id_check">Проверить</button>
                </div>
            </section>
            <section class="col" hidden id="id_results">
                <h2>Результат</h2>
                <p>Статус: <span id="id_ok"></span></p>
                <div>
                    <span>Пояснение: </span>
                    <pre id="id_description" style="border: 1px solid red; padding: 1em"></pre>
                </div>
                <p>Тайминг: <span id="id_timing"></span> мс</p>
            </section>
        </div>
        <div class="row">
            <section class="col">
                <h2>ФОРМУЛА УСПЕХА</h2>
                <p>
                    Успех &mdash; это когда ваш сервис работает правильно (см. ниже)
                    и решает следующую задачу:
                </p>
                <blockquote class="blockquote">
                    <p>Если сервису прислать число, то сервис его как-то запомнит.</p>
                    <p>Если сервису прислать слово <code>"stop"</code>,<br>то сервис выведет текущую сумму из предыдущих
                       чисел.</p>
                </blockquote>
                <p>Это общая идея, а детали реализации смотри дальше.</p>
                <p>
                    <span class="badge rounded-pill bg-warning text-dark">⚠</span>
                    <i>МОЙ сервис тестирует ВАШ сервис!</i>
                    <br>
                    <span class="badge rounded-pill bg-warning text-dark">⚠</span>
                    <i>Пункты ниже относятся к ВАШЕМУ сервису.</i>
                </p>
                <p>
                    Пункты ДОЛЖНЫ быть реализованы в полном объёме.
                    <a href="https://datatracker.ietf.org/doc/html/rfc2119">
                        <span class="badge bg-info text-dark">RFC 2119</span>
                    </a>
                </p>
                <ol>
                    <li>Сервис ОБЯЗАН быть онлайн.</li>
                    <li>Сервис ОБЯЗАН ответить на запрос не дольше чем за 4 секунды.</li>
                    <li>
                        <p>Сервис ОБЯЗАН принимать HTTP запросы на путь <code>/task4/</code>.</p>
                        <p><i>Пункты ниже относятся к <code>/task4/</code>.</i></p>
                        <ol>
                            <li>
                                Сервис ОБЯЗАН разрешать только метод <code>POST</code>.
                                <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST"><sup>🔎</sup></a>
                                <br>
                                На любые другие методы сервис ОБЯЗАН ответить статусом:
                                <code>405 Method Not Allowed</code>.
                                <a href="https://httpstatuses.com/405"><sup>🔎</sup></a>
                            </li>
                            <li>Сервис ОБЯЗАН читать имя пользователя из заголовка
                                <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers"><sup>🔎</sup></a>
                                <code>X-USER</code>.
                                <br>
                                Если заголовока нет, или он пустой, пользователь считается анонимным.
                                <br>
                                На запрос анонимного пользователя сервер ОБЯЗАН ответить статусом:
                                <code>403 Forbidden</code>.
                                <a href="https://httpstatuses.com/403"><sup>🔎</sup></a>
                            </li>
                            <li>Сервис ОБЯЗАН принимать данные
                                в теле запроса
                                <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages"><sup>🔎</sup></a>
                                только в формате JSON.
                                <a href="https://www.json.org/json-ru.html"><sup>🔎</sup></a>
                                <br>
                                На запрос без тела сервис ОБЯЗАН ответить статусом:
                                <code>422 Unprocessable Entity</code>.
                                <a href="https://httpstatuses.com/422"><sup>🔎</sup></a>
                                <br>
                                На запрос с телом не в формате JSON сервис ОБЯЗАН ответить статусом:
                                <code>422 Unprocessable Entity</code>.
                                <a href="https://httpstatuses.com/422"><sup>🔎</sup></a>
                            </li>
                            <li>
                                Сервис ОБЯЗАН накапливать числа или подсчитывать сумму только для чисел определённого
                                пользователя.
                                <br>
                                Сервис ОБЯЗАН НЕ выдавать данные одного пользователя другому пользователю.
                            </li>
                            <li>Сервис ОБЯЗАН принимать только строку <code>"stop"</code>
                                или целые числа в диапазоне: <code>[-100, 100]</code>.
                                <br>
                                На любые другие данные сервис ОБЯЗАН ответить статусом:
                                <code>422 Unprocessable Entity</code>.
                                <a href="https://httpstatuses.com/422"><sup>🔎</sup></a>
                            </li>
                        </ol>
                    </li>
                </ol>
            </section>
            <section class="col-4">
                <h2>Десятка проверок</h2>
                <table class="table table-borderless table-hover">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Юзер</th>
                        <th scope="col">Сервис</th>
                        <th scope="col">Время</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for check in object_list %}
                        <tr class="{{ check.ok|yesno:"table-success," }}">
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ check.name }}</td>
                            <td>{{ check.service }}</td>
                            <td>{{ check.at|timezone:"Europe/Minsk"|date:"H:i @ j E Y, l" }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </section>
        </div>
    </article>
</div>
<script defer src="{% static 'task4/checks.js' %}"></script>
</body>
</html>

superproject/task4/templates/task4/numbers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ object_list }}
</body>
</html>