superproject/blog/urls.py
from django.urls import include
from django.urls import path
from rest_framework import routers

from blog import views

app_name = "blog"

router = routers.DefaultRouter()
router.register("posts", views.PostViewSet)

urlpatterns = [
    path("", views.AllPostsView.as_view(), name="all"),
    path("<int:pk>/", views.SinglePostView.as_view(), name="single"),
    path("<int:pk>/delete/", views.DeletePostView.as_view(), name="delete"),
    path("<int:pk>/update/", views.UpdatePostView.as_view(), name="update"),
    path("api/", include(router.urls)),
    path("new/", views.CreatePostView.as_view(), name="new"),
]

superproject/project/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.urls import include
from django.urls import path

from project.views import SignUpView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("task4/", include("task4.urls")),
]

superproject/blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse_lazy

User = get_user_model()


class Post(models.Model):
    title = models.TextField()
    content = models.TextField(blank=True, null=True)
    hidden = models.BooleanField(default=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self) -> str:
        return reverse_lazy("blog:single", kwargs={"pk": self.pk})

    def __repr__(self):
        lock_sign = "🔒" if self.hidden else ""
        class_name = self.__class__.__name__
        kwargs = {
            "pk": self.pk,
            "title": self.title,
        }
        kwargs_text_parts = (f"{arg}={value!r}" for arg, value in kwargs.items())
        kwargs_text = ", ".join(kwargs_text_parts)

        return f"{lock_sign}{class_name}({kwargs_text})"

    __str__ = __repr__

superproject/blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView
from rest_framework import serializers
from rest_framework import viewsets

from blog.models import Post

PAGE_SIZE = 50


class BlogMixin:
    fields = ["title", "content", "hidden"]
    model = Post
    success_url = reverse_lazy("blog:all")


class OwnerMixin:
    def get_queryset(self):
        return super().get_queryset().filter(author=self.request.user)


class AllPostsView(BlogMixin, ListView):
    def get_queryset(self):
        return super().get_queryset().filter(hidden=False).order_by("pk")[:PAGE_SIZE]


class SinglePostView(BlogMixin, DetailView):
    pass


class CreatePostView(LoginRequiredMixin, BlogMixin, CreateView):
    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()
        return super().form_valid(form)


class UpdatePostView(LoginRequiredMixin, BlogMixin, OwnerMixin, UpdateView):
    pass


class DeletePostView(LoginRequiredMixin, BlogMixin, OwnerMixin, DeleteView):
    pass


# -------------------------


class PostSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Post
        depth = 1
        fields = ["id", "title", "content", "hidden", "author_id"]


class PostViewSet(viewsets.ModelViewSet):
    lookup_field = "id"
    queryset = Post.objects.all()
    serializer_class = PostSerializer

superproject/blog/templates/blog/post_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if object.author == user %}
    <p>Удаляем {{ object }}</p>
    <p>Ты уверен?</p>
    <form method="POST">
        {% csrf_token %}
        <button type="submit">Да</button>
    </form>
    <p><a href="{% url 'blog:all' %}">(назад ко всем постам)</a></p>
{% endif %}
</body>
</html>

superproject/blog/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<article>
    <h1>{{ object.title }}</h1>
    <a href="{% url 'blog:all' %}">(back to all posts)</a>
    {% if object.author == user %}
        <a href="{% url 'blog:update' object.pk %}">(edit post)</a>
        <a href="{% url 'blog:delete' object.pk %}">(delete post)</a>
    {% endif %}
    <hr>
    <p>{{ post.content|default:"(no content)" }}</p>
</article>
</body>
</html>

superproject/blog/templates/blog/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if user.is_authenticated %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>
{% endif %}
</body>
</html>

superproject/blog/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
    <p>&#123; me: "{{ user }}" &#125;</p>
    <p><a href="{% url 'blog:post-list' %}">API</a></p>
    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">logOut()</a>
    {% else %}
        <a href="{% url 'login' %}">logIn()</a>
        <a href="{% url 'signup' %}">signUp()</a>
    {% endif %}
</div>

<article>
    <h1>All posts</h1>
    {% if not user.is_anonymous %}
        <a href="{% url 'blog:new' %}">New post</a>
    {% endif %}
    <hr>
    {% for post in object_list %}
        <section id="id_post_{{ post.pk }}">
            <a href="{{ post.get_absolute_url }}"><h2>{{ post.title }}</h2></a>
            <p>{{ post.content|default:"(no content)" }}</p>
            <p>Author: {{ post.author }}</p>
        </section>
    {% empty %}
        <p>ø</p>
    {% endfor %}
</article>
</body>
</html>